### ISSUE TITLE
Annotated tags in history

### ISSUE THREAD

**Issue by kyrias** [lericson/pylibmc#182]
Could you change back to making proper annotated tagged releases that are in the branch history so that `git describe` works properly? Otherwise it will make getting the version in git packages much more annoying.

**Comment by lericson** [comment]
I stopped? Probably just forgot to push.

- Ludvig (phone)

**Comment by kyrias** [comment]
No tags since `1.1.1` have been part of the history of `master`. For one you can see this by looking at the annotation for the tags after it and see that they're not in the git log.

**Comment by lericson** [comment]
I pushed 1.4.2 as an annotated tag. Can't really help you with `git describe`'s behavior though. :disappointed:

**Comment by kyrias** [comment]
You pushed it, but you’ve still not tagged it on top of master. What do you do when you tag releases?

**Comment by lericson** [comment]
I create a commit with the new version number, then tag that commit, make a release to PyPI and then push the tag to Github. The reason git-describe isn't finding the correct tag is that the tag isn't on what the manual refers to as a "reachable commit."

-Ludvig

**Comment by kyrias** [comment]
Any reason you don’t make said commit on master?

**Comment by lericson** [comment]
It became an issue when HEAD contained an actual version number, people would get confused about which version they were running. To alleviate this problem, the version number in master is always x.y.100-dev.

I have to ask, why is git-describe so important to you? :-)

-Ludvig

**Comment by kyrias** [comment]
How did people get confused by /that/ o.O

Anyway, it’s the only way to reliably get the version information from a git repo, and the only reliable way to get the version for the package being built.

**Comment by lericson** [comment]
I think the canonical way for setuptools-type of packages is

	python setup.py --version

-Ludvig

**Comment by kyrias** [comment]
For one that requires you to actually update `pylibmc-version.h` with the new version after every release, and at that point you might as well properly tag on master and then append a `dev` suffix to the version in a followup commit instead. Either way it doesn’t actually give the useful output that `git describe` does.

**Comment by lericson** [comment]
I'm intrigued by the idea of not having a file to keep track of the current version! The way I see it, the requirements are as follows:

- Version number must be known at runtime (Cf _pylibmc.__version__)
- One release must correspond to one Git commit exactly, and must have the proper version tag
- The version number reported by master must indicate that it is not the released version, and preferably indicate what the most recent release is (i.e. development is based on what version.)

I think the current scheme of things satisfies all of this without incurring too much overhead. I'm all ears if you have other suggestions.

-Ludvig
